env:
  global:
  - GIT_NAME: "'Markdown autodeploy'"
  - GIT_EMAIL: jovart.arthur@gmail.com
  - GH_REF: git@github.com:DuckHunt-discord/DHV2.git
language: python
before_script:
- pip install -r requirements.txt
- pip install pybabel
script:
- pybabel extract -o language/EN/LC_MESSAGES/default.po ./
- for dirr in ./language/* ; do msgfmt ${dirr}/LC_MESSAGES/default.po -o ${dirr}/LC_MESSAGES/default.mo ; echo ${dirr} compiled; done
- openssl aes-256-cbc -K $encrypted_03e55cc3139f_key -iv $encrypted_03e55cc3139f_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- git config user.name "travis-ci - Automatic Publish"
- git config user.email "${GIT_EMAIL}"
- git remote add gh-token "${GH_REF}";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; git push origin master gh-token; fi;
